# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Nightly WildFly backward compatibility with JDK11, used up to WF 34.

on:
  workflow_call:
    inputs:
      wildfly-ref:
        description: "WildFly branch/tag"
        required: false
        default: "main"
        type: string
jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v2
      - name: print latest_commit
        run: echo ${{ github.sha }}
      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"
  galleon-plugins-build:
    name: galleon-plugins-${{ matrix.os }}-jdk${{ matrix.java }}
    runs-on: ${{ matrix.os }}
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    outputs:
      galleon-plugins-version: ${{ steps.version.outputs.galleon-plugins-version }}
      galleon-version: ${{ steps.version.outputs.galleon-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: ['11', '17']
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Build and Test Galleon plugins on ${{ matrix.java }}
        run: mvn -U -B -ntp clean install
        shell: bash
      - id: version
        run: |
          echo "galleon-plugins-version=$(mvn -B help:evaluate -Dexpression=project.version -DforceStdout -q)" >> $GITHUB_OUTPUT
          echo "galleon-version=$(mvn -B help:evaluate -Dexpression=version.org.jboss.galleon -DforceStdout -q)" >> $GITHUB_OUTPUT
      - name: Archive the repository
        if: matrix.java == '11'
        run:  |
          cd ~
          find ./.m2/repository -type d -name "*SNAPSHOT" -print0 | xargs -0 tar -czf ~/galleon-plugins-maven-repository.tar.gz  
      - uses: actions/upload-artifact@v4
        if: matrix.java == '11'
        with:
          name: galleon-plugins-maven-repository
          path: ~/galleon-plugins-maven-repository.tar.gz
          retention-days: 5
      - name: Upload Test Reports on Failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}
          path: '**/surefire-reports/*.txt'

  wildfly-build-and-test:
    name: Linux/Windows - JDK11 and JDK17
    uses: wildfly/wildfly/.github/workflows/shared-wildfly-build-and-test.yml@34.0.0.Final
    needs: [check_date, galleon-plugins-build]
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    with:
      build-arguments: '-fae -Dversion.org.jboss.galleon=${{needs.galleon-plugins-build.outputs.galleon-version}} -Dversion.org.wildfly.galleon-plugins=${{needs.galleon-plugins-build.outputs.galleon-plugins-version}} -Dversion.org.wildfly.plugin=5.1.0.Alpha2 -Dversion.org.wildfly.wildfly-channel-plugin=1.0.20 -Dversion.org.wildfly.bom-builder-plugin=2.0.8.Final'
      java-versions: "['11', '17']"
      os: "['ubuntu-latest', 'windows-latest']"
      maven-repo-name: galleon-plugins-maven-repository
      maven-repo-path: galleon-plugins-maven-repository.tar.gz
      ref: ${{ inputs.wildfly-ref }}
 
  wildfly-build-and-test-galleon-layers:
    name: Galleon Linux - JDK11
    uses: wildfly/wildfly/.github/workflows/shared-wildfly-build-and-test.yml@34.0.0.Final
    needs: [check_date, galleon-plugins-build]
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    with:
      test-arguments: '-fae -Dts.layers -Dts.galleon'
      build-arguments: '-Dversion.org.jboss.galleon=${{needs.galleon-plugins-build.outputs.galleon-version}} -Dversion.org.wildfly.galleon-plugins=${{needs.galleon-plugins-build.outputs.galleon-plugins-version}} -Dversion.org.wildfly.plugin=5.1.0.Alpha2 -Dversion.org.wildfly.wildfly-channel-plugin=1.0.20 -Dversion.org.wildfly.bom-builder-plugin=2.0.8.Final'
      os: "['ubuntu-latest']"
      java-versions: "['11']"
      maven-repo-name: galleon-plugins-maven-repository
      maven-repo-path: galleon-plugins-maven-repository.tar.gz
      ref: ${{ inputs.wildfly-ref }}
  
  wildfly-build-and-test-preview:
    name: WildFly Preview - Linux- JDK17
    uses: wildfly/wildfly/.github/workflows/shared-wildfly-build-and-test.yml@34.0.0.Final
    needs: [check_date, galleon-plugins-build]
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    with:
      test-arguments: '-fae -Dts.preview'
      build-arguments: '-Dversion.org.jboss.galleon=${{needs.galleon-plugins-build.outputs.galleon-version}} -Dversion.org.wildfly.galleon-plugins=${{needs.galleon-plugins-build.outputs.galleon-plugins-version}} -Dversion.org.wildfly.plugin=5.1.0.Alpha2 -Dversion.org.wildfly.wildfly-channel-plugin=1.0.20 -Dversion.org.wildfly.bom-builder-plugin=2.0.8.Final'
      java-versions: "['17']"
      os: "['ubuntu-latest']"
      maven-repo-name: galleon-plugins-maven-repository
      maven-repo-path: galleon-plugins-maven-repository.tar.gz
      ref: ${{ inputs.wildfly-ref }}
  
  datasources-build-and-test:
    name: WildFly Datasources galleon-pack build and test
    runs-on: ${{ matrix.os }}
    needs: [check_date, galleon-plugins-build]
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: ['17']
    steps:
    - uses: actions/checkout@v4
      with:
        repository: wildfly-extras/wildfly-datasources-galleon-pack
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: 'maven'
    - uses: actions/download-artifact@v4.1.7
      with:
        name: galleon-plugins-maven-repository
        path: .
    - name: Extract Maven Repo
      shell: bash
      run: |
         tar -xzf galleon-plugins-maven-repository.tar.gz -C ~
    - name: Build and Test WildFly Datasources galleon-pack with SNAPSHOT build of galleon-plugins
      run: mvn clean install -Dversion.org.wildfly.galleon-plugins=${{needs.galleon-plugins-build.outputs.galleon-plugins-version}}
      shell: bash
    - name: Upload Test Reports on Failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}
        path: '**/surefire-reports/*.txt'
